# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuario: bcrypt
        
    #role_hierarchy:
    #    ROLE_USER:    ROLE_USER
    #    ROLE_ADMIN:       ROLE_USER_SUP
    #    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_USER_SUP, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        api_provider:
            entity:
                class: AppBundle:Usuario
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        
        api:
            pattern: ^/api/(?!token)
            methods: [POST,PUT,DELETE]
            guard:
                authenticators:
                    - app.jwt_token_authenticator
            #anonymous: false
        
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
                    
                    
    access_control:
        - { path: /api/token-authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: /api/products, roles: [ROLE_USER] }
        #- { path: /api/product, roles: [ROLE_USER] }
        #- { path: ^/api, roles: [ROLE_USER] }
